name: 'Update PPA'
description: 'Publish latest version of Gama to the apt repository/ppa'
inputs:
  tag:  
    description: "Release tag name"
    required: true

  is_pre_release:
    description: "Is this a pre-release?"
    default: "false"

runs:
  using: composite
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Login to ghcr.io
      uses: docker/login-action@v3.0.0
      with: 
        registry: ghcr.io
        username: ${{ secrets.BOT_GH_NAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push alpha docker image
      if : ${{ steps.pre_release_check.outputs.is_pre_release }} == 'true'
      uses: docker/build-push-action@v5
      working-directory: ./docker/alpha
      with:
        context: . #in /docker/${{ inputs.tag }} thx to working-directory
        push: true
        # GHCR.io replaces docker.pkg.github.com
        tags: |
          ghcr.io/gama-platform/gama:${{ inputs.tag }}
          ghcr.io/gama-platform/gama:alpha

          docker.pkg.github.com/gama-platform/gama.docker/gama:${{ inputs.tag }}
          docker.pkg.github.com/gama-platform/gama.docker/gama:alpha

          gama-platform/gama:${{ inputs.tag }}
          gama-platform/gama:alpha

    # TODO

    # - name: Build & Push stable docker image
    #   if : ${{ steps.pre_release_check.outputs.is_pre_release }} == 'false'
    #   uses: docker/build-push-action@v5
    #   working-directory: ./docker/${{ inputs.tag }}
    #   with:
    #     context: .
    #     push: true
    #     # GHCR.io replaces docker.pkg.github.com
    #     tags: |
    #       ghcr.io/gama-platform/gama:${{ inputs.tag }}
    #       ghcr.io/gama-platform/gama:latest

    #       docker.pkg.github.com/gama-platform/gama.docker/gama:${{ inputs.tag }}
    #       docker.pkg.github.com/gama-platform/gama.docker/gama:latest

    #       gama-platform/gama:${{ inputs.tag }}
    #       gama-platform/gama:latest